### ISSUE TITLE
Fix up loose ends around first part of content migration

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1319]
## Objective

The Guides & Tutorials section is fully migrated. Though all references (`g.doc('...')`) are currently broken and the migrated documents all use sometimes deprecated macros. This needs to be fixed.

## Tasks
- [x] Write a small utility to automatically fix references
- [x] Implement import for missing documents from ampproject/amphtml
- [x] Add in missing macros and rewrite those that have a new syntax

**Comment by matthiasrohmer** [comment]
Fixed all broken references (try running `node platform/lib/pipeline/growReferenceChecker.js` after moving around content) and implemented the missing importer for single paths from `ampproject/amphtml`.

I have also migrated all macros to the new BBCode syntax by simple search and replace except of `image()` and `anim()`. They live in `frontend/templates/layouts/default.j2` and need to be replaced later.

**Comment by matthiasrohmer** [comment]
Will be further handled in #1328.
