### ISSUE TITLE
Implement filtering of pages by format

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1321]
## Objective

The user should be able to filter some sections by selecting one of the formats websites, ads, stories or email in the sidebar. The page's content should change dependent on the selected format.

## Tasks
- [ ] Implement on-the-fly filtering for local development
- [x] Implement static filter mechanism
- [ ] Write manual on how to manually maintain a format variant (remember `$hidden`)
- [ ] Make component sidebar also use new format-toggle

**Comment by matthiasrohmer** [comment]
The static filtering works fairly well now. Also with pages that are manually maintained. See (`content/amp-dev/documentation/guides-and-tutorials/**index.ads.md**|**index.md**).

But for local development the manual ones are not yet evaluated. This would require the proxy to ask Grow if there is one before doing a on-the-fly rewrite but this seems nasty... Maybe I have a better idea over the holidays.

**Comment by matthiasrohmer** [comment]
Manually filtered pages should have `$hidden: true` in their frontmatter. Because currently they are appearing in the sidebar.

**Comment by matthiasrohmer** [comment]
Filtering now also works seamlessly during development. Additionally the ugly-duckling-pills got a face lift: 
<img width="261" alt="bildschirmfoto 2019-01-02 um 20 44 15" src="https://user-images.githubusercontent.com/12857772/50633916-3fdf2d80-0f4d-11e9-863c-19d89af99d33.png">
