### ISSUE TITLE
Overhaul repository structure

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1349]
## Objective

While all things come in place we figured out that the current repository structure has some shortcomings that could be fixed.

## Background

During prototype phase the `platform` package was a good starting point to hold all logic to serve and build amp.dev. After the integration of `playground` and abe.com as `examples` it makes sense to also dissolve `platform` in more specific entities.

## Tasks
- [x] Move `platform/package.json` and `platform/app.yaml` into repository root
- [ ] Move `platform/config` to repository root
- [ ] Create `build` directory to encapsulate build logic
- [ ] Extract content from Grow pod and move Grow structure to `build`
- [ ] Build into designated `dist` folder instead of scattering build artifacts

**Comment by matthiasrohmer** [comment]
Is ongoing and doesn't need to be tracked separately.

**Comment by pbakaus** [comment]
I'd love for this to be prioritized @sebastianbenz @matthiasrohmer.

In addition to the bullet points in the description, I also think that some of our directories are overly deep, like `pages/content/amp-dev/documentation`. I wish we could flatten a lot of it.
